/*
  ==============================================================================

    PatreonBackers.h

    Special thanks to our Patreon supporters who make these plugins possible!

    Do NOT hand-edit the tier arrays below. They are generated from the live
    Patreon campaign by scripts/update-patrons.py (run it before a release, or
    let CI run it — the setup job in .github/workflows/build.yml refreshes this
    header and every release build ships the current list). To move a name or
    change a display spelling, use the "name_overrides" map in the script's
    config rather than editing here, or your edit will be overwritten.

        scripts/update-patrons.py            # refresh from Patreon, rewrite this file
        scripts/update-patrons.py --dry-run  # preview, write nothing

    The script also keeps sibling worktrees that carry this header in sync
    (plugins-main / plugins-worktree / plugins-multi-synth), so credits stay
    consistent across worktrees.

    Tier Benefits:
    - Hugs ($1/month):       Development updates, name in credits
    - Supporter ($3/month):  Development updates, name in credits
    - Patron ($5/month):     Development updates, name in credits
    - Champion ($10/month):  Development updates, name in credits

  ==============================================================================
*/

#pragma once

// Support both JuceHeader.h (generated by juce_generate_juce_header) and direct module includes
#if __has_include(<JuceHeader.h>)
    #include <JuceHeader.h>
#else
    #include <juce_core/juce_core.h>
#endif

#include <vector>

namespace PatreonCredits
{
    //==========================================================================
    // Backer Lists
    //==========================================================================

    // Champion ($10/month)
    inline const std::vector<juce::String> champions = {
    };

    // Patron ($5/month)
    inline const std::vector<juce::String> patrons = {
        "danboy",
        "David",
        "nuertine DIGEL",
    };

    // Supporter ($3/month)
    inline const std::vector<juce::String> supporters = {
        "Beau Landry",
        "Eblen Macari",
        "Jano",
        "Manav",
        "Someone64",
    };

    // Hugs ($1/month)
    inline const std::vector<juce::String> hugs = {
        "Adrienne",
        "Andre C",
        "Benjamin Walker",
        "Chaumontet Olivier",
        "Codey",
        "Dusk Audio",
        "fennek",
        "fisHkiD76",
        "Jon Skarin",
        "LEONID FEDOROV",
        "Samantha Druker",
    };

    // Past Supporters — thank you for your support!
    inline const std::vector<juce::String> pastSupporters = {
        "mister-universe",
        "S C",
        "Stefan Windus",
    };

    //==========================================================================
    // Helper Functions
    //==========================================================================

    /** Get all backers formatted for display in credits/about dialogs */
    inline juce::String getAllBackersFormatted()
    {
        juce::String result;

        if (!champions.empty())
        {
            result += "CHAMPIONS\n\n";
            for (const auto& name : champions)
                result += name + "\n";
            result += "\n";
        }

        if (!patrons.empty())
        {
            result += "PATRONS\n\n";
            for (const auto& name : patrons)
                result += name + "\n";
            result += "\n";
        }

        if (!supporters.empty())
        {
            result += "SUPPORTERS\n\n";
            for (const auto& name : supporters)
                result += name + "\n";
        }

        if (!hugs.empty())
        {
            result += "\nHUGS\n\n";
            for (const auto& name : hugs)
                result += name + "\n";
        }

        if (!pastSupporters.empty())
        {
            result += "\nPAST SUPPORTERS\n\n";
            for (const auto& name : pastSupporters)
                result += name + "\n";
        }

        if (result.isEmpty())
            result = "Be the first to support development on Patreon!\n\nYour name could be here!";

        return result;
    }

    /** Get total number of backers across all tiers */
    inline int getTotalBackerCount()
    {
        return static_cast<int>(champions.size() + patrons.size() +
                                supporters.size() + hugs.size() +
                                pastSupporters.size());
    }
}
