#pragma once
#ifndef MULTICOMP2_VERSION_MAJOR
# define MULTICOMP2_VERSION_MAJOR 0
#endif
#ifndef MULTICOMP2_VERSION_MINOR
# define MULTICOMP2_VERSION_MINOR 1
#endif
#ifndef MULTICOMP2_VERSION_PATCH
# define MULTICOMP2_VERSION_PATCH 0
#endif
#define MULTICOMP2_STRINGIFY_IMPL(x) #x
#define MULTICOMP2_STRINGIFY(x) MULTICOMP2_STRINGIFY_IMPL(x)
#define MULTICOMP2_VERSION_STRING MULTICOMP2_STRINGIFY(MULTICOMP2_VERSION_MAJOR) "." MULTICOMP2_STRINGIFY(MULTICOMP2_VERSION_MINOR) "." MULTICOMP2_STRINGIFY(MULTICOMP2_VERSION_PATCH)
