// Copyright (C) 2026 Dusk Audio - GNU GPL v3.0 or later (see repository LICENSE).
// Third-party components in the built plugins (DPF - ISC; Dear ImGui - MIT; and
// others) are attributed in plugins/shared-dpf/THIRD_PARTY_LICENSES.md.
//
// MultiSynthParams.hpp - GENERATED by tools gen_params.py; do not hand-edit the
// tables. One X-macro list (MSYNTH_PARAMS) drives the DPF param enum, the
// initParameter() metadata, and the engine setter dispatch. The DPF parameter
// index equals the core msynth::Param index 1:1 (verified by static_assert in
// MultiSynthPlugin.cpp), so forwarding is a single dsp.setParameter(index,value).
//
// KIND: LIN linear float, LOG logarithmic float (min>0), INT integer choice,
// BOOL on/off. Two output params (peak L/R for meters) follow the core params.

#pragma once

// X(EnumSuffix, symbol, Name, min, max, default, KIND)
#define MSYNTH_PARAMS(X) \
    X(Mode, "mode", "Mode", 0.0f, 5.0f, 0.0f, INT) \
    X(MasterTune, "masterTune", "Master Tune", -100.0f, 100.0f, 0.0f, LIN) \
    X(MasterVol, "masterVol", "Master Volume", -60.0f, 6.0f, 0.0f, LIN) \
    X(MasterPan, "masterPan", "Master Pan", -1.0f, 1.0f, 0.0f, LIN) \
    X(StereoWidth, "stereoWidth", "Stereo Width", 0.0f, 1.0f, 0.5f, LIN) \
    X(Oversampling, "oversampling", "Oversampling", 0.0f, 2.0f, 1.0f, INT) \
    X(AnalogAmt, "analogAmt", "Analog", 0.0f, 1.0f, 0.2f, LIN) \
    X(Vintage, "vintage", "Vintage", 0.0f, 1.0f, 0.0f, LIN) \
    X(Osc1Wave, "osc1Wave", "Osc 1 Wave", 0.0f, 4.0f, 0.0f, INT) \
    X(Osc1Detune, "osc1Detune", "Osc 1 Detune", -50.0f, 50.0f, 0.0f, LIN) \
    X(Osc1PW, "osc1PW", "Osc 1 PW", 0.05f, 0.95f, 0.5f, LIN) \
    X(Osc1Level, "osc1Level", "Osc 1 Level", 0.0f, 1.0f, 1.0f, LIN) \
    X(Osc2Wave, "osc2Wave", "Osc 2 Wave", 0.0f, 4.0f, 0.0f, INT) \
    X(Osc2Detune, "osc2Detune", "Osc 2 Detune", -50.0f, 50.0f, 7.0f, LIN) \
    X(Osc2PW, "osc2PW", "Osc 2 PW", 0.05f, 0.95f, 0.5f, LIN) \
    X(Osc2Level, "osc2Level", "Osc 2 Level", 0.0f, 1.0f, 0.8f, LIN) \
    X(Osc2Semi, "osc2Semi", "Osc 2 Semi", -24.0f, 24.0f, 0.0f, INT) \
    X(Osc3Wave, "osc3Wave", "Osc 3 Wave", 0.0f, 3.0f, 0.0f, INT) \
    X(Osc3Level, "osc3Level", "Osc 3 Level", 0.0f, 1.0f, 0.5f, LIN) \
    X(SubLevel, "subLevel", "Sub Level", 0.0f, 1.0f, 0.5f, LIN) \
    X(SubWave, "subWave", "Sub Wave", 0.0f, 1.0f, 0.0f, INT) \
    X(NoiseLevel, "noiseLevel", "Noise Level", 0.0f, 1.0f, 0.0f, LIN) \
    X(FilterCutoff, "filterCutoff", "Filter Cutoff", 20.0f, 20000.0f, 8000.0f, LOG) \
    X(FilterRes, "filterRes", "Filter Resonance", 0.0f, 1.0f, 0.3f, LIN) \
    X(FilterHP, "filterHP", "Filter HP", 20.0f, 2000.0f, 20.0f, LOG) \
    X(FilterEnvAmt, "filterEnvAmt", "Filter Env Amt", -1.0f, 1.0f, 0.5f, LIN) \
    X(AmpA, "ampA", "Amp Attack", 0.001f, 10.0f, 0.01f, LOG) \
    X(AmpD, "ampD", "Amp Decay", 0.001f, 10.0f, 0.2f, LOG) \
    X(AmpS, "ampS", "Amp Sustain", 0.0f, 1.0f, 0.8f, LIN) \
    X(AmpR, "ampR", "Amp Release", 0.001f, 10.0f, 0.3f, LOG) \
    X(AmpCurve, "ampCurve", "Amp Curve", 0.0f, 3.0f, 3.0f, INT) \
    X(FiltA, "filtA", "Filter Attack", 0.001f, 10.0f, 0.01f, LOG) \
    X(FiltD, "filtD", "Filter Decay", 0.001f, 10.0f, 0.3f, LOG) \
    X(FiltS, "filtS", "Filter Sustain", 0.0f, 1.0f, 0.4f, LIN) \
    X(FiltR, "filtR", "Filter Release", 0.001f, 10.0f, 0.5f, LOG) \
    X(FiltCurve, "filtCurve", "Filter Curve", 0.0f, 3.0f, 3.0f, INT) \
    X(CrossMod, "crossMod", "Cross Mod", 0.0f, 1.0f, 0.0f, LIN) \
    X(RingMod, "ringMod", "Ring Mod", 0.0f, 1.0f, 0.0f, LIN) \
    X(HardSync, "hardSync", "Hard Sync", 0.0f, 1.0f, 0.0f, BOOL) \
    X(FMAmount, "fmAmount", "FM Amount", 0.0f, 1.0f, 0.0f, LIN) \
    X(PmFenvOscA, "pmFenvOscA", "PM FEnv-OscA", 0.0f, 1.0f, 0.0f, LIN) \
    X(PmFenvFilt, "pmFenvFilt", "PM FEnv-Filt", 0.0f, 1.0f, 0.0f, LIN) \
    X(PmOscBOscA, "pmOscBOscA", "PM OscB-OscA", 0.0f, 1.0f, 0.0f, LIN) \
    X(PmOscBPWM, "pmOscBPWM", "PM OscB-PW", 0.0f, 1.0f, 0.0f, LIN) \
    X(ShRate, "shRate", "S&H Rate", 0.1f, 50.0f, 5.0f, LOG) \
    X(CosmosChorus, "cosmosChorus", "Chorus Mode", 0.0f, 3.0f, 3.0f, INT) \
    X(Lfo1Rate, "lfo1Rate", "LFO 1 Rate", 0.01f, 50.0f, 1.0f, LOG) \
    X(Lfo1Shape, "lfo1Shape", "LFO 1 Shape", 0.0f, 4.0f, 0.0f, INT) \
    X(Lfo1Fade, "lfo1Fade", "LFO 1 Fade", 0.0f, 5.0f, 0.0f, LIN) \
    X(Lfo1Sync, "lfo1Sync", "LFO 1 Sync", 0.0f, 1.0f, 0.0f, BOOL) \
    X(Lfo2Rate, "lfo2Rate", "LFO 2 Rate", 0.01f, 50.0f, 0.5f, LOG) \
    X(Lfo2Shape, "lfo2Shape", "LFO 2 Shape", 0.0f, 4.0f, 0.0f, INT) \
    X(Lfo2Fade, "lfo2Fade", "LFO 2 Fade", 0.0f, 5.0f, 0.0f, LIN) \
    X(Lfo2Sync, "lfo2Sync", "LFO 2 Sync", 0.0f, 1.0f, 0.0f, BOOL) \
    X(UnisonVoices, "unisonVoices", "Unison Voices", 1.0f, 8.0f, 1.0f, INT) \
    X(UnisonDetune, "unisonDetune", "Unison Detune", 0.0f, 50.0f, 10.0f, LIN) \
    X(UnisonSpread, "unisonSpread", "Unison Spread", 0.0f, 1.0f, 1.0f, LIN) \
    X(PortaTime, "portaTime", "Portamento", 0.0f, 2.0f, 0.0f, LIN) \
    X(Legato, "legato", "Legato", 0.0f, 1.0f, 0.0f, BOOL) \
    X(GlideMode, "glideMode", "Glide Mode", 0.0f, 1.0f, 0.0f, INT) \
    X(VelSens, "velSens", "Velocity Sens", 0.0f, 1.0f, 0.7f, LIN) \
    X(VelCurve, "velCurve", "Vel Curve", 0.0f, 3.0f, 0.0f, INT) \
    X(PbRange, "pbRange", "PB Range", 1.0f, 24.0f, 2.0f, INT) \
    X(ArpOn, "arpOn", "Arp On", 0.0f, 1.0f, 0.0f, BOOL) \
    X(ArpMode, "arpMode", "Arp Mode", 0.0f, 6.0f, 0.0f, INT) \
    X(ArpOctave, "arpOctave", "Arp Octave", 1.0f, 4.0f, 1.0f, INT) \
    X(ArpRate, "arpRate", "Arp Rate", 0.0f, 13.0f, 3.0f, INT) \
    X(ArpGate, "arpGate", "Arp Gate", 0.01f, 1.0f, 0.5f, LIN) \
    X(ArpSwing, "arpSwing", "Arp Swing", 0.0f, 1.0f, 0.0f, LIN) \
    X(ArpLatch, "arpLatch", "Arp Latch", 0.0f, 1.0f, 0.0f, BOOL) \
    X(ArpVelMode, "arpVelMode", "Arp Vel Mode", 0.0f, 2.0f, 0.0f, INT) \
    X(ArpFixedVel, "arpFixedVel", "Arp Fixed Vel", 1.0f, 127.0f, 100.0f, INT) \
    X(ArpStep0, "arpStep0", "Arp Step 1", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep1, "arpStep1", "Arp Step 2", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep2, "arpStep2", "Arp Step 3", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep3, "arpStep3", "Arp Step 4", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep4, "arpStep4", "Arp Step 5", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep5, "arpStep5", "Arp Step 6", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep6, "arpStep6", "Arp Step 7", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep7, "arpStep7", "Arp Step 8", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep8, "arpStep8", "Arp Step 9", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep9, "arpStep9", "Arp Step 10", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep10, "arpStep10", "Arp Step 11", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep11, "arpStep11", "Arp Step 12", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep12, "arpStep12", "Arp Step 13", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep13, "arpStep13", "Arp Step 14", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep14, "arpStep14", "Arp Step 15", 0.0f, 1.0f, 1.0f, BOOL) \
    X(ArpStep15, "arpStep15", "Arp Step 16", 0.0f, 1.0f, 1.0f, BOOL) \
    X(DriveOn, "driveOn", "Drive On", 0.0f, 1.0f, 0.0f, BOOL) \
    X(DriveType, "driveType", "Drive Type", 0.0f, 2.0f, 0.0f, INT) \
    X(DriveAmt, "driveAmt", "Drive Amount", 0.0f, 1.0f, 0.3f, LIN) \
    X(DriveMix, "driveMix", "Drive Mix", 0.0f, 1.0f, 1.0f, LIN) \
    X(ChorusOn, "chorusOn", "Chorus On", 0.0f, 1.0f, 0.0f, BOOL) \
    X(ChorusRate, "chorusRate", "Chorus Rate", 0.1f, 10.0f, 0.8f, LOG) \
    X(ChorusDepth, "chorusDepth", "Chorus Depth", 0.0f, 1.0f, 0.5f, LIN) \
    X(ChorusMix, "chorusMix", "Chorus Mix", 0.0f, 1.0f, 0.5f, LIN) \
    X(DelayOn, "delayOn", "Delay On", 0.0f, 1.0f, 0.0f, BOOL) \
    X(DelaySync, "delaySync", "Delay Sync", 0.0f, 1.0f, 1.0f, BOOL) \
    X(DelayTime, "delayTime", "Delay Time", 1.0f, 2000.0f, 500.0f, LOG) \
    X(DelayDiv, "delayDiv", "Delay Division", 0.0f, 13.0f, 3.0f, INT) \
    X(DelayFB, "delayFB", "Delay Feedback", 0.0f, 0.95f, 0.3f, LIN) \
    X(DelayMix, "delayMix", "Delay Mix", 0.0f, 1.0f, 0.3f, LIN) \
    X(DelayPP, "delayPP", "Delay Ping-Pong", 0.0f, 1.0f, 0.0f, BOOL) \
    X(DelayTape, "delayTape", "Delay Tape", 0.0f, 1.0f, 0.0f, BOOL) \
    X(ReverbOn, "reverbOn", "Reverb On", 0.0f, 1.0f, 0.0f, BOOL) \
    X(ReverbSize, "reverbSize", "Reverb Size", 0.0f, 1.0f, 0.5f, LIN) \
    X(ReverbDecay, "reverbDecay", "Reverb Decay", 0.1f, 20.0f, 2.0f, LOG) \
    X(ReverbDamp, "reverbDamp", "Reverb Damping", 0.0f, 1.0f, 0.3f, LIN) \
    X(ReverbMix, "reverbMix", "Reverb Mix", 0.0f, 1.0f, 0.2f, LIN) \
    X(ReverbPD, "reverbPD", "Reverb Pre-Delay", 0.0f, 200.0f, 20.0f, LIN) \
    X(ModSrc0, "modSrc0", "Mod 1 Source", 0.0f, 10.0f, 0.0f, INT) \
    X(ModSrc1, "modSrc1", "Mod 2 Source", 0.0f, 10.0f, 0.0f, INT) \
    X(ModSrc2, "modSrc2", "Mod 3 Source", 0.0f, 10.0f, 0.0f, INT) \
    X(ModSrc3, "modSrc3", "Mod 4 Source", 0.0f, 10.0f, 0.0f, INT) \
    X(ModSrc4, "modSrc4", "Mod 5 Source", 0.0f, 10.0f, 0.0f, INT) \
    X(ModSrc5, "modSrc5", "Mod 6 Source", 0.0f, 10.0f, 0.0f, INT) \
    X(ModSrc6, "modSrc6", "Mod 7 Source", 0.0f, 10.0f, 0.0f, INT) \
    X(ModSrc7, "modSrc7", "Mod 8 Source", 0.0f, 10.0f, 0.0f, INT) \
    X(ModDst0, "modDst0", "Mod 1 Dest", 0.0f, 12.0f, 0.0f, INT) \
    X(ModDst1, "modDst1", "Mod 2 Dest", 0.0f, 12.0f, 0.0f, INT) \
    X(ModDst2, "modDst2", "Mod 3 Dest", 0.0f, 12.0f, 0.0f, INT) \
    X(ModDst3, "modDst3", "Mod 4 Dest", 0.0f, 12.0f, 0.0f, INT) \
    X(ModDst4, "modDst4", "Mod 5 Dest", 0.0f, 12.0f, 0.0f, INT) \
    X(ModDst5, "modDst5", "Mod 6 Dest", 0.0f, 12.0f, 0.0f, INT) \
    X(ModDst6, "modDst6", "Mod 7 Dest", 0.0f, 12.0f, 0.0f, INT) \
    X(ModDst7, "modDst7", "Mod 8 Dest", 0.0f, 12.0f, 0.0f, INT) \
    X(ModAmt0, "modAmt0", "Mod 1 Amount", -1.0f, 1.0f, 0.0f, LIN) \
    X(ModAmt1, "modAmt1", "Mod 2 Amount", -1.0f, 1.0f, 0.0f, LIN) \
    X(ModAmt2, "modAmt2", "Mod 3 Amount", -1.0f, 1.0f, 0.0f, LIN) \
    X(ModAmt3, "modAmt3", "Mod 4 Amount", -1.0f, 1.0f, 0.0f, LIN) \
    X(ModAmt4, "modAmt4", "Mod 5 Amount", -1.0f, 1.0f, 0.0f, LIN) \
    X(ModAmt5, "modAmt5", "Mod 6 Amount", -1.0f, 1.0f, 0.0f, LIN) \
    X(ModAmt6, "modAmt6", "Mod 7 Amount", -1.0f, 1.0f, 0.0f, LIN) \
    X(ModAmt7, "modAmt7", "Mod 8 Amount", -1.0f, 1.0f, 0.0f, LIN) \
    X(PrismAlgo, "prismAlgo", "Prism Algorithm", 0.0f, 7.0f, 4.0f, INT) \
    X(PrismFB, "prismFB", "Prism Feedback", 0.0f, 1.0f, 0.0f, LIN) \
    X(Op1Ratio, "op1Ratio", "Op 1 Ratio", 0.25f, 16.0f, 1.0f, LOG) \
    X(Op1Fine, "op1Fine", "Op 1 Fine", -100.0f, 100.0f, 0.0f, LIN) \
    X(Op1Level, "op1Level", "Op 1 Level", 0.0f, 1.0f, 1.0f, LIN) \
    X(Op1Vel, "op1Vel", "Op 1 Vel Sens", 0.0f, 1.0f, 0.0f, LIN) \
    X(Op1KeyScale, "op1KeyScale", "Op 1 Key Scale", -1.0f, 1.0f, 0.0f, LIN) \
    X(Op1A, "op1A", "Op 1 Attack", 0.001f, 10.0f, 0.005f, LOG) \
    X(Op1D, "op1D", "Op 1 Decay", 0.001f, 10.0f, 0.4f, LOG) \
    X(Op1S, "op1S", "Op 1 Sustain", 0.0f, 1.0f, 0.7f, LIN) \
    X(Op1R, "op1R", "Op 1 Release", 0.001f, 10.0f, 0.4f, LOG) \
    X(Op2Ratio, "op2Ratio", "Op 2 Ratio", 0.25f, 16.0f, 1.0f, LOG) \
    X(Op2Fine, "op2Fine", "Op 2 Fine", -100.0f, 100.0f, 0.0f, LIN) \
    X(Op2Level, "op2Level", "Op 2 Level", 0.0f, 1.0f, 0.5f, LIN) \
    X(Op2Vel, "op2Vel", "Op 2 Vel Sens", 0.0f, 1.0f, 0.0f, LIN) \
    X(Op2KeyScale, "op2KeyScale", "Op 2 Key Scale", -1.0f, 1.0f, 0.0f, LIN) \
    X(Op2A, "op2A", "Op 2 Attack", 0.001f, 10.0f, 0.005f, LOG) \
    X(Op2D, "op2D", "Op 2 Decay", 0.001f, 10.0f, 0.4f, LOG) \
    X(Op2S, "op2S", "Op 2 Sustain", 0.0f, 1.0f, 0.7f, LIN) \
    X(Op2R, "op2R", "Op 2 Release", 0.001f, 10.0f, 0.4f, LOG) \
    X(Op3Ratio, "op3Ratio", "Op 3 Ratio", 0.25f, 16.0f, 1.0f, LOG) \
    X(Op3Fine, "op3Fine", "Op 3 Fine", -100.0f, 100.0f, 0.0f, LIN) \
    X(Op3Level, "op3Level", "Op 3 Level", 0.0f, 1.0f, 0.8f, LIN) \
    X(Op3Vel, "op3Vel", "Op 3 Vel Sens", 0.0f, 1.0f, 0.0f, LIN) \
    X(Op3KeyScale, "op3KeyScale", "Op 3 Key Scale", -1.0f, 1.0f, 0.0f, LIN) \
    X(Op3A, "op3A", "Op 3 Attack", 0.001f, 10.0f, 0.005f, LOG) \
    X(Op3D, "op3D", "Op 3 Decay", 0.001f, 10.0f, 0.4f, LOG) \
    X(Op3S, "op3S", "Op 3 Sustain", 0.0f, 1.0f, 0.7f, LIN) \
    X(Op3R, "op3R", "Op 3 Release", 0.001f, 10.0f, 0.4f, LOG) \
    X(Op4Ratio, "op4Ratio", "Op 4 Ratio", 0.25f, 16.0f, 1.0f, LOG) \
    X(Op4Fine, "op4Fine", "Op 4 Fine", -100.0f, 100.0f, 0.0f, LIN) \
    X(Op4Level, "op4Level", "Op 4 Level", 0.0f, 1.0f, 0.5f, LIN) \
    X(Op4Vel, "op4Vel", "Op 4 Vel Sens", 0.0f, 1.0f, 0.0f, LIN) \
    X(Op4KeyScale, "op4KeyScale", "Op 4 Key Scale", -1.0f, 1.0f, 0.0f, LIN) \
    X(Op4A, "op4A", "Op 4 Attack", 0.001f, 10.0f, 0.005f, LOG) \
    X(Op4D, "op4D", "Op 4 Decay", 0.001f, 10.0f, 0.4f, LOG) \
    X(Op4S, "op4S", "Op 4 Sustain", 0.0f, 1.0f, 0.7f, LIN) \
    X(Op4R, "op4R", "Op 4 Release", 0.001f, 10.0f, 0.4f, LOG) \
    X(AcidAccentAmt, "acidAccentAmt", "Acid Accent", 0.0f, 1.0f, 0.7f, LIN) \
    X(AcidSlideTime, "acidSlideTime", "Acid Slide", 10.0f, 200.0f, 60.0f, LOG) \
    X(SeqPitch0, "seqPitch0", "Seq Pitch 1", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch1, "seqPitch1", "Seq Pitch 2", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch2, "seqPitch2", "Seq Pitch 3", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch3, "seqPitch3", "Seq Pitch 4", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch4, "seqPitch4", "Seq Pitch 5", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch5, "seqPitch5", "Seq Pitch 6", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch6, "seqPitch6", "Seq Pitch 7", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch7, "seqPitch7", "Seq Pitch 8", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch8, "seqPitch8", "Seq Pitch 9", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch9, "seqPitch9", "Seq Pitch 10", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch10, "seqPitch10", "Seq Pitch 11", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch11, "seqPitch11", "Seq Pitch 12", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch12, "seqPitch12", "Seq Pitch 13", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch13, "seqPitch13", "Seq Pitch 14", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch14, "seqPitch14", "Seq Pitch 15", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqPitch15, "seqPitch15", "Seq Pitch 16", -24.0f, 24.0f, 0.0f, INT) \
    X(SeqAccent0, "seqAccent0", "Seq Accent 1", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent1, "seqAccent1", "Seq Accent 2", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent2, "seqAccent2", "Seq Accent 3", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent3, "seqAccent3", "Seq Accent 4", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent4, "seqAccent4", "Seq Accent 5", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent5, "seqAccent5", "Seq Accent 6", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent6, "seqAccent6", "Seq Accent 7", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent7, "seqAccent7", "Seq Accent 8", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent8, "seqAccent8", "Seq Accent 9", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent9, "seqAccent9", "Seq Accent 10", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent10, "seqAccent10", "Seq Accent 11", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent11, "seqAccent11", "Seq Accent 12", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent12, "seqAccent12", "Seq Accent 13", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent13, "seqAccent13", "Seq Accent 14", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent14, "seqAccent14", "Seq Accent 15", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqAccent15, "seqAccent15", "Seq Accent 16", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide0, "seqSlide0", "Seq Slide 1", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide1, "seqSlide1", "Seq Slide 2", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide2, "seqSlide2", "Seq Slide 3", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide3, "seqSlide3", "Seq Slide 4", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide4, "seqSlide4", "Seq Slide 5", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide5, "seqSlide5", "Seq Slide 6", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide6, "seqSlide6", "Seq Slide 7", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide7, "seqSlide7", "Seq Slide 8", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide8, "seqSlide8", "Seq Slide 9", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide9, "seqSlide9", "Seq Slide 10", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide10, "seqSlide10", "Seq Slide 11", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide11, "seqSlide11", "Seq Slide 12", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide12, "seqSlide12", "Seq Slide 13", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide13, "seqSlide13", "Seq Slide 14", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide14, "seqSlide14", "Seq Slide 15", 0.0f, 1.0f, 0.0f, BOOL) \
    X(SeqSlide15, "seqSlide15", "Seq Slide 16", 0.0f, 1.0f, 0.0f, BOOL)

// Parameter index enum (kParam<Suffix>), matching the core order 1:1.
enum ParamId
{
#define X(suf, sym, name, mn, mx, df, kind) kParam##suf,
    MSYNTH_PARAMS(X)
#undef X
    kNumCoreParams,                 // == msynth::kNumParams (222)
    kParamOutLevelL = kNumCoreParams, // output: peak L (meter fallback)
    kParamOutLevelR,                  // output: peak R
    kParamCount
};

enum ParamKind { PK_LIN = 0, PK_LOG, PK_INT, PK_BOOL };
struct ParamDef { const char* symbol; const char* name; float min, max, def; int kind; };
static constexpr ParamDef kParamDefs[kNumCoreParams] =
{
#define LIN  PK_LIN
#define LOG  PK_LOG
#define INT  PK_INT
#define BOOL PK_BOOL
#define X(suf, sym, name, mn, mx, df, kind) { sym, name, mn, mx, df, kind },
    MSYNTH_PARAMS(X)
#undef X
#undef LIN
#undef LOG
#undef INT
#undef BOOL
};

// ---------------------------------------------------------------------------
// Factory presets (54) - static override table. loadProgram() resets every
// param to its default, applies the shared baseline, then the per-preset
// overrides. Every preset ships at 2x oversampling (baseline oversampling=1);
// the pitch bug is fixed so 2x is correct. Phase 5 re-voiced the original 40
// (unity-gain filter fix + level/intent) and appended new preset banks; see
// docs/dpf-migration/09-multi-synth-presets.md for the per-preset change log.
// ---------------------------------------------------------------------------
struct PresetRow { int index; float value; };

static constexpr PresetRow kPresetBaseline[] = { { kParamMasterVol, 0.0f }, { kParamOsc1Wave, 0.0f }, { kParamOsc2Wave, 0.0f }, { kParamOsc1Detune, 0.0f }, { kParamOsc2Detune, 7.0f }, { kParamOsc1Level, 0.8f }, { kParamOsc2Level, 0.6f }, { kParamNoiseLevel, 0.0f }, { kParamFilterCutoff, 8000.0f }, { kParamFilterRes, 0.3f }, { kParamFilterEnvAmt, 0.5f }, { kParamAmpA, 0.01f }, { kParamAmpD, 0.2f }, { kParamAmpS, 0.8f }, { kParamAmpR, 0.3f }, { kParamCrossMod, 0.0f }, { kParamRingMod, 0.0f }, { kParamPmFenvOscA, 0.0f }, { kParamPmFenvFilt, 0.0f }, { kParamPmOscBOscA, 0.0f }, { kParamPmOscBPWM, 0.0f }, { kParamArpOn, 0.0f }, { kParamDriveOn, 0.0f }, { kParamChorusOn, 0.0f }, { kParamDelayOn, 0.0f }, { kParamReverbOn, 0.0f }, { kParamUnisonVoices, 1.0f }, { kParamPortaTime, 0.0f }, { kParamAnalogAmt, 0.2f }, { kParamVintage, 0.0f }, { kParamOversampling, 1.0f } };

static constexpr PresetRow kP00[] = { { kParamMode, 0.0f }, { kParamOsc1Wave, 0.0f }, { kParamOsc2Wave, 4.0f }, { kParamOsc2Detune, 8.0f }, { kParamFilterCutoff, 2500.0f }, { kParamFilterRes, 0.15f }, { kParamFilterEnvAmt, 0.3f }, { kParamAmpA, 0.4f }, { kParamAmpD, 0.6f }, { kParamAmpS, 0.85f }, { kParamAmpR, 1.8f }, { kParamCosmosChorus, 3.0f }, { kParamAnalogAmt, 0.3f }, { kParamReverbOn, 1.0f }, { kParamReverbSize, 0.6f }, { kParamReverbMix, 0.2f } };
static constexpr PresetRow kP01[] = { { kParamMode, 0.0f }, { kParamFilterCutoff, 5000.0f }, { kParamFilterRes, 0.35f }, { kParamAmpA, 0.005f }, { kParamAmpD, 0.25f }, { kParamAmpS, 0.5f }, { kParamAmpR, 0.6f }, { kParamCosmosChorus, 1.0f }, { kParamArpOn, 1.0f }, { kParamArpRate, 3.0f }, { kParamArpGate, 0.6f }, { kParamDelayOn, 1.0f }, { kParamDelayMix, 0.2f } };
static constexpr PresetRow kP02[] = { { kParamMode, 0.0f }, { kParamFilterCutoff, 1200.0f }, { kParamFilterRes, 0.25f }, { kParamFilterEnvAmt, 0.15f }, { kParamAmpA, 1.0f }, { kParamAmpS, 0.9f }, { kParamAmpR, 2.5f }, { kParamCosmosChorus, 2.0f }, { kParamVintage, 0.5f } };
static constexpr PresetRow kP03[] = { { kParamMode, 0.0f }, { kParamOsc2Detune, 15.0f }, { kParamFilterCutoff, 3500.0f }, { kParamAmpA, 0.25f }, { kParamAmpS, 0.8f }, { kParamAmpR, 1.5f }, { kParamCosmosChorus, 3.0f }, { kParamAnalogAmt, 0.35f } };
static constexpr PresetRow kP04[] = { { kParamMode, 0.0f }, { kParamFilterCutoff, 6000.0f }, { kParamFilterRes, 0.2f }, { kParamAmpA, 0.003f }, { kParamAmpD, 0.12f }, { kParamAmpS, 0.2f }, { kParamAmpR, 0.35f }, { kParamCosmosChorus, 3.0f }, { kParamArpOn, 1.0f }, { kParamArpRate, 4.0f }, { kParamArpGate, 0.3f }, { kParamDelayOn, 1.0f }, { kParamDelayMix, 0.25f }, { kParamReverbOn, 1.0f }, { kParamReverbMix, 0.2f } };
static constexpr PresetRow kP05[] = { { kParamMasterVol, -3.0f }, { kParamMode, 1.0f }, { kParamFilterCutoff, 2000.0f }, { kParamFilterRes, 0.4f }, { kParamFilterEnvAmt, 0.7f }, { kParamFiltA, 0.05f }, { kParamFiltD, 0.3f }, { kParamFiltS, 0.3f }, { kParamAmpA, 0.01f }, { kParamAmpD, 0.3f }, { kParamAmpS, 0.7f }, { kParamPmFenvFilt, 0.3f } };
static constexpr PresetRow kP06[] = { { kParamMasterVol, -1.5f }, { kParamMode, 1.0f }, { kParamFilterCutoff, 3000.0f }, { kParamFilterRes, 0.2f }, { kParamAmpA, 0.005f }, { kParamAmpD, 0.4f }, { kParamAmpS, 0.5f }, { kParamAmpR, 0.3f } };
static constexpr PresetRow kP07[] = { { kParamMode, 1.0f }, { kParamOsc2Wave, 2.0f }, { kParamOsc2Semi, 7.0f }, { kParamPmOscBOscA, 0.5f }, { kParamPmFenvOscA, 0.4f }, { kParamFilterCutoff, 5000.0f }, { kParamAmpA, 0.005f }, { kParamAmpD, 1.0f }, { kParamAmpS, 0.0f }, { kParamAmpR, 1.5f }, { kParamReverbOn, 1.0f }, { kParamReverbMix, 0.35f }, { kParamReverbDecay, 3.0f } };
static constexpr PresetRow kP08[] = { { kParamMode, 1.0f }, { kParamFilterCutoff, 1200.0f }, { kParamFilterRes, 0.5f }, { kParamFilterEnvAmt, 0.3f }, { kParamAmpA, 0.5f }, { kParamAmpS, 0.85f }, { kParamAmpR, 1.5f }, { kParamVintage, 0.3f }, { kParamPmFenvFilt, 0.2f } };
static constexpr PresetRow kP09[] = { { kParamMode, 1.0f }, { kParamFilterCutoff, 4000.0f }, { kParamFilterEnvAmt, 0.6f }, { kParamAmpA, 0.001f }, { kParamAmpD, 0.15f }, { kParamAmpS, 0.0f }, { kParamAmpR, 0.1f }, { kParamPmFenvOscA, 0.3f } };
static constexpr PresetRow kP10[] = { { kParamMode, 2.0f }, { kParamOsc1Wave, 4.0f }, { kParamOsc2Wave, 0.0f }, { kParamOsc2Semi, -12.0f }, { kParamFilterCutoff, 600.0f }, { kParamFilterRes, 0.55f }, { kParamFilterEnvAmt, 0.5f }, { kParamSubLevel, 0.9f }, { kParamFiltA, 0.001f }, { kParamFiltD, 0.15f }, { kParamFiltS, 0.05f }, { kParamArpOn, 1.0f }, { kParamArpRate, 3.0f }, { kParamVintage, 0.3f } };
static constexpr PresetRow kP11[] = { { kParamMode, 2.0f }, { kParamFilterCutoff, 400.0f }, { kParamFilterRes, 0.85f }, { kParamFilterEnvAmt, 0.95f }, { kParamFiltA, 0.001f }, { kParamFiltD, 0.15f }, { kParamFiltS, 0.0f }, { kParamSubLevel, 0.7f }, { kParamPortaTime, 0.08f }, { kParamAmpD, 0.3f }, { kParamAmpS, 0.0f }, { kParamAmpR, 0.15f } };
static constexpr PresetRow kP12[] = { { kParamMasterVol, -3.0f }, { kParamMode, 2.0f }, { kParamFilterCutoff, 6000.0f }, { kParamFilterRes, 0.3f }, { kParamAmpA, 0.005f }, { kParamPortaTime, 0.1f }, { kParamDriveOn, 1.0f }, { kParamDriveAmt, 0.4f }, { kParamDelayOn, 1.0f }, { kParamDelayMix, 0.2f } };
static constexpr PresetRow kP13[] = { { kParamMode, 2.0f }, { kParamOsc1Wave, 3.0f }, { kParamOsc2Wave, 3.0f }, { kParamFilterCutoff, 400.0f }, { kParamSubLevel, 1.0f }, { kParamNoiseLevel, 0.02f } };
static constexpr PresetRow kP14[] = { { kParamMode, 2.0f }, { kParamOsc2Semi, 7.0f }, { kParamFilterCutoff, 800.0f }, { kParamFilterRes, 0.6f }, { kParamFilterEnvAmt, 0.7f }, { kParamFiltA, 0.01f }, { kParamFiltD, 0.4f }, { kParamRingMod, 0.3f }, { kParamDelayOn, 1.0f }, { kParamDelayMix, 0.2f } };
static constexpr PresetRow kP15[] = { { kParamMode, 1.0f }, { kParamOsc1Wave, 0.0f }, { kParamOsc2Wave, 0.0f }, { kParamOsc1Detune, 0.0f }, { kParamOsc2Detune, 8.0f }, { kParamOsc2Level, 0.8f }, { kParamFilterCutoff, 2000.0f }, { kParamFilterRes, 0.3f }, { kParamFilterEnvAmt, 0.25f }, { kParamFiltA, 0.01f }, { kParamFiltD, 0.3f }, { kParamFiltS, 0.5f }, { kParamAmpA, 0.005f }, { kParamAmpD, 0.3f }, { kParamAmpS, 0.7f }, { kParamAmpR, 0.4f }, { kParamArpOn, 1.0f }, { kParamArpMode, 2.0f }, { kParamArpRate, 3.0f }, { kParamArpOctave, 1.0f }, { kParamArpGate, 0.6f }, { kParamArpLatch, 1.0f }, { kParamLfo1Rate, 0.3f }, { kParamLfo1Shape, 0.0f }, { kParamModSrc0, 1.0f }, { kParamModDst0, 5.0f }, { kParamModAmt0, 0.15f }, { kParamDelayOn, 1.0f }, { kParamDelaySync, 1.0f }, { kParamDelayDiv, 3.0f }, { kParamDelayMix, 0.2f }, { kParamDelayFB, 0.3f }, { kParamReverbOn, 1.0f }, { kParamReverbSize, 0.5f }, { kParamReverbMix, 0.15f }, { kParamStereoWidth, 0.7f } };
static constexpr PresetRow kP16[] = { { kParamMode, 3.0f }, { kParamFMAmount, 0.6f }, { kParamHardSync, 1.0f }, { kParamOsc2Semi, 19.0f }, { kParamFilterCutoff, 3000.0f }, { kParamAmpA, 0.001f }, { kParamAmpD, 0.08f }, { kParamAmpS, 0.0f }, { kParamArpOn, 1.0f }, { kParamArpRate, 4.0f }, { kParamArpMode, 4.0f }, { kParamArpGate, 0.2f } };
static constexpr PresetRow kP17[] = { { kParamMode, 3.0f }, { kParamRingMod, 0.6f }, { kParamFMAmount, 0.2f }, { kParamOsc2Semi, -5.0f }, { kParamOsc3Wave, 0.0f }, { kParamOsc3Level, 0.5f }, { kParamFilterCutoff, 800.0f }, { kParamFilterRes, 0.65f }, { kParamAmpA, 3.0f }, { kParamAmpS, 1.0f }, { kParamAmpR, 5.0f }, { kParamReverbOn, 1.0f }, { kParamReverbDecay, 10.0f }, { kParamReverbMix, 0.5f }, { kParamVintage, 0.7f } };
static constexpr PresetRow kP18[] = { { kParamMode, 3.0f }, { kParamFMAmount, 0.8f }, { kParamHardSync, 1.0f }, { kParamOsc2Semi, 12.0f }, { kParamFilterCutoff, 2500.0f }, { kParamFilterEnvAmt, 0.4f }, { kParamFiltA, 0.5f }, { kParamFiltD, 2.0f }, { kParamFiltS, 0.2f }, { kParamAmpA, 0.8f }, { kParamAmpR, 3.0f }, { kParamVintage, 0.5f }, { kParamDelayOn, 1.0f }, { kParamDelayTape, 1.0f }, { kParamDelayMix, 0.3f } };
static constexpr PresetRow kP19[] = { { kParamMode, 3.0f }, { kParamFilterCutoff, 2500.0f }, { kParamFilterEnvAmt, 0.7f }, { kParamArpOn, 1.0f }, { kParamArpRate, 3.0f }, { kParamArpGate, 0.5f }, { kParamDelayOn, 1.0f }, { kParamDelayTape, 1.0f } };
static constexpr PresetRow kP20[] = { { kParamMode, 0.0f }, { kParamFilterCutoff, 1800.0f }, { kParamFilterRes, 0.35f }, { kParamFilterEnvAmt, 0.25f }, { kParamAmpA, 0.5f }, { kParamAmpS, 0.85f }, { kParamAmpR, 2.0f }, { kParamCosmosChorus, 2.0f }, { kParamDriveOn, 1.0f }, { kParamDriveAmt, 0.3f }, { kParamDelayOn, 1.0f }, { kParamDelayTape, 1.0f }, { kParamDelayMix, 0.25f }, { kParamStereoWidth, 0.7f } };
static constexpr PresetRow kP21[] = { { kParamMode, 0.0f }, { kParamFilterCutoff, 7000.0f }, { kParamAmpA, 0.003f }, { kParamAmpD, 0.2f }, { kParamAmpS, 0.3f }, { kParamAmpR, 0.5f }, { kParamCosmosChorus, 3.0f }, { kParamArpOn, 1.0f }, { kParamArpMode, 4.0f }, { kParamArpRate, 4.0f }, { kParamArpOctave, 3.0f }, { kParamArpGate, 0.4f }, { kParamDelayOn, 1.0f }, { kParamDelayMix, 0.3f }, { kParamReverbOn, 1.0f }, { kParamReverbMix, 0.25f }, { kParamStereoWidth, 0.8f } };
static constexpr PresetRow kP22[] = { { kParamMode, 1.0f }, { kParamFilterCutoff, 1500.0f }, { kParamFilterRes, 0.3f }, { kParamFilterEnvAmt, 0.6f }, { kParamFiltA, 0.03f }, { kParamFiltD, 0.25f }, { kParamFiltS, 0.35f }, { kParamAmpA, 0.01f }, { kParamAmpS, 0.75f }, { kParamPmFenvFilt, 0.4f }, { kParamPmFenvOscA, 0.15f }, { kParamVelCurve, 2.0f } };
static constexpr PresetRow kP23[] = { { kParamMode, 1.0f }, { kParamOsc2Wave, 2.0f }, { kParamOsc2Semi, 19.0f }, { kParamFilterCutoff, 6000.0f }, { kParamAmpA, 0.001f }, { kParamAmpD, 1.5f }, { kParamAmpS, 0.0f }, { kParamAmpR, 2.0f }, { kParamPmOscBOscA, 0.6f }, { kParamPmFenvOscA, 0.3f }, { kParamReverbOn, 1.0f }, { kParamReverbDecay, 4.0f }, { kParamReverbMix, 0.35f } };
static constexpr PresetRow kP24[] = { { kParamMode, 2.0f }, { kParamOsc1Wave, 0.0f }, { kParamFilterCutoff, 350.0f }, { kParamFilterRes, 0.9f }, { kParamFilterEnvAmt, 0.95f }, { kParamFiltA, 0.001f }, { kParamFiltD, 0.12f }, { kParamFiltS, 0.0f }, { kParamAmpD, 0.2f }, { kParamAmpS, 0.0f }, { kParamPortaTime, 0.06f }, { kParamGlideMode, 1.0f }, { kParamArpOn, 1.0f }, { kParamArpRate, 3.0f }, { kParamArpGate, 0.6f } };
static constexpr PresetRow kP25[] = { { kParamMode, 2.0f }, { kParamOsc1Wave, 3.0f }, { kParamOsc2Wave, 3.0f }, { kParamOsc2Semi, -12.0f }, { kParamFilterCutoff, 200.0f }, { kParamFilterRes, 0.15f }, { kParamSubLevel, 1.0f }, { kParamSubWave, 1.0f }, { kParamAmpA, 0.01f }, { kParamAmpS, 1.0f }, { kParamVelCurve, 1.0f } };
static constexpr PresetRow kP26[] = { { kParamMode, 3.0f }, { kParamFilterCutoff, 2000.0f }, { kParamFilterRes, 0.5f }, { kParamFilterEnvAmt, 0.4f }, { kParamShRate, 8.0f }, { kParamArpOn, 1.0f }, { kParamArpRate, 3.0f }, { kParamArpMode, 0.0f }, { kParamArpOctave, 2.0f }, { kParamDelayOn, 1.0f }, { kParamDelayMix, 0.2f } };
static constexpr PresetRow kP27[] = { { kParamMode, 3.0f }, { kParamFMAmount, 0.7f }, { kParamRingMod, 0.4f }, { kParamHardSync, 1.0f }, { kParamOsc2Semi, 7.0f }, { kParamFilterCutoff, 4000.0f }, { kParamFilterRes, 0.4f }, { kParamAmpA, 0.3f }, { kParamAmpR, 2.0f }, { kParamNoiseLevel, 0.1f }, { kParamReverbOn, 1.0f }, { kParamReverbDecay, 5.0f }, { kParamReverbMix, 0.4f }, { kParamVintage, 0.4f } };
static constexpr PresetRow kP28[] = { { kParamMode, 0.0f }, { kParamOsc1Wave, 2.0f }, { kParamOsc2Wave, 3.0f }, { kParamFilterCutoff, 4000.0f }, { kParamAmpA, 0.005f }, { kParamAmpD, 0.8f }, { kParamAmpS, 0.3f }, { kParamAmpR, 0.5f }, { kParamCosmosChorus, 1.0f }, { kParamVelCurve, 2.0f } };
static constexpr PresetRow kP29[] = { { kParamMode, 1.0f }, { kParamFilterCutoff, 3000.0f }, { kParamFilterRes, 0.15f }, { kParamAmpA, 0.8f }, { kParamAmpS, 0.9f }, { kParamAmpR, 1.5f }, { kParamUnisonVoices, 4.0f }, { kParamUnisonDetune, 12.0f }, { kParamStereoWidth, 0.7f }, { kParamChorusOn, 1.0f }, { kParamChorusMix, 0.3f } };
static constexpr PresetRow kP30[] = { { kParamMode, 2.0f }, { kParamFilterCutoff, 600.0f }, { kParamFilterRes, 0.6f }, { kParamSubLevel, 0.8f }, { kParamLfo1Rate, 4.0f }, { kParamLfo1Shape, 0.0f }, { kParamModSrc0, 1.0f }, { kParamModDst0, 5.0f }, { kParamModAmt0, 0.6f } };
static constexpr PresetRow kP31[] = { { kParamMasterVol, -2.0f }, { kParamMode, 2.0f }, { kParamFilterCutoff, 5000.0f }, { kParamFilterRes, 0.25f }, { kParamAmpA, 0.005f }, { kParamPortaTime, 0.12f }, { kParamGlideMode, 1.0f }, { kParamDriveOn, 1.0f }, { kParamDriveAmt, 0.25f }, { kParamDelayOn, 1.0f }, { kParamDelayTape, 1.0f }, { kParamDelayMix, 0.25f }, { kParamDelayFB, 0.4f } };
static constexpr PresetRow kP32[] = { { kParamMode, 3.0f }, { kParamFMAmount, 0.3f }, { kParamOsc3Level, 0.6f }, { kParamOsc3Wave, 3.0f }, { kParamFilterCutoff, 1200.0f }, { kParamFilterRes, 0.55f }, { kParamAmpA, 3.0f }, { kParamAmpS, 1.0f }, { kParamAmpR, 5.0f }, { kParamLfo1Rate, 0.1f }, { kParamModSrc0, 1.0f }, { kParamModDst0, 5.0f }, { kParamModAmt0, 0.4f }, { kParamReverbOn, 1.0f }, { kParamReverbDecay, 12.0f }, { kParamReverbMix, 0.5f }, { kParamVintage, 0.6f } };
static constexpr PresetRow kP33[] = { { kParamMode, 0.0f }, { kParamFilterCutoff, 4500.0f }, { kParamFilterRes, 0.3f }, { kParamFilterEnvAmt, 0.4f }, { kParamFiltD, 0.2f }, { kParamAmpA, 0.003f }, { kParamAmpD, 0.15f }, { kParamAmpS, 0.4f }, { kParamAmpR, 0.3f }, { kParamCosmosChorus, 3.0f }, { kParamArpOn, 1.0f }, { kParamArpMode, 2.0f }, { kParamArpRate, 4.0f }, { kParamArpOctave, 3.0f }, { kParamArpGate, 0.5f }, { kParamArpSwing, 0.3f }, { kParamDelayOn, 1.0f }, { kParamDelayMix, 0.2f } };
static constexpr PresetRow kP34[] = { { kParamMasterVol, -3.5f }, { kParamMode, 1.0f }, { kParamOsc2Semi, 7.0f }, { kParamFilterCutoff, 3500.0f }, { kParamFilterRes, 0.2f }, { kParamAmpA, 0.01f }, { kParamAmpS, 0.8f }, { kParamUnisonVoices, 3.0f }, { kParamUnisonDetune, 8.0f }, { kParamStereoWidth, 0.65f } };
static constexpr PresetRow kP35[] = { { kParamMode, 3.0f }, { kParamOsc1Level, 0.0f }, { kParamOsc2Level, 0.0f }, { kParamNoiseLevel, 1.0f }, { kParamFilterCutoff, 500.0f }, { kParamFilterRes, 0.7f }, { kParamFilterEnvAmt, 0.8f }, { kParamFiltA, 0.5f }, { kParamFiltD, 2.0f }, { kParamFiltS, 0.1f }, { kParamAmpA, 0.3f }, { kParamAmpS, 0.7f }, { kParamAmpR, 3.0f }, { kParamReverbOn, 1.0f }, { kParamReverbMix, 0.4f } };
static constexpr PresetRow kP36[] = { { kParamMode, 0.0f }, { kParamCosmosChorus, 3.0f } };
static constexpr PresetRow kP37[] = { { kParamMasterVol, -4.0f }, { kParamMode, 1.0f } };
static constexpr PresetRow kP38[] = { { kParamMode, 2.0f } };
static constexpr PresetRow kP39[] = { { kParamMode, 3.0f } };
static constexpr PresetRow kP40[] = { { kParamMasterVol, -2.0f }, { kParamMode, 4.0f }, { kParamPrismAlgo, 4.0f }, { kParamPrismFB, 0.0f }, { kParamOp1Ratio, 1.0f }, { kParamOp1Level, 1.0f }, { kParamOp1A, 0.001f }, { kParamOp1D, 2.0f }, { kParamOp1S, 0.4f }, { kParamOp1R, 0.4f }, { kParamOp2Ratio, 1.0f }, { kParamOp2Level, 0.45f }, { kParamOp2A, 0.001f }, { kParamOp2D, 1.2f }, { kParamOp2S, 0.2f }, { kParamOp2R, 0.3f }, { kParamOp3Ratio, 1.0f }, { kParamOp3Level, 0.85f }, { kParamOp3A, 0.001f }, { kParamOp3D, 1.5f }, { kParamOp3S, 0.25f }, { kParamOp3R, 0.4f }, { kParamOp4Ratio, 14.0f }, { kParamOp4Level, 0.7f }, { kParamOp4KeyScale, -0.35f }, { kParamOp4A, 0.001f }, { kParamOp4D, 0.12f }, { kParamOp4S, 0.0f }, { kParamOp4R, 0.2f }, { kParamFilterCutoff, 14000.0f }, { kParamFilterEnvAmt, 0.0f }, { kParamAmpA, 0.001f }, { kParamAmpD, 2.5f }, { kParamAmpS, 0.25f }, { kParamAmpR, 0.5f }, { kParamChorusOn, 1.0f }, { kParamChorusMix, 0.25f } };
static constexpr PresetRow kP41[] = { { kParamMode, 4.0f }, { kParamPrismAlgo, 0.0f }, { kParamPrismFB, 0.15f }, { kParamOp1Ratio, 1.0f }, { kParamOp1Level, 1.0f }, { kParamOp1A, 0.001f }, { kParamOp1D, 0.5f }, { kParamOp1S, 0.6f }, { kParamOp1R, 0.2f }, { kParamOp2Ratio, 1.0f }, { kParamOp2Level, 0.5f }, { kParamOp2A, 0.001f }, { kParamOp2D, 0.3f }, { kParamOp2S, 0.2f }, { kParamOp2R, 0.2f }, { kParamOp3Ratio, 1.0f }, { kParamOp3Level, 0.35f }, { kParamOp3A, 0.001f }, { kParamOp3D, 0.25f }, { kParamOp3S, 0.1f }, { kParamOp3R, 0.2f }, { kParamOp4Ratio, 2.0f }, { kParamOp4Level, 0.4f }, { kParamOp4A, 0.001f }, { kParamOp4D, 0.2f }, { kParamOp4S, 0.1f }, { kParamOp4R, 0.2f }, { kParamFilterCutoff, 4000.0f }, { kParamFilterRes, 0.2f }, { kParamFilterEnvAmt, 0.35f }, { kParamFiltA, 0.001f }, { kParamFiltD, 0.3f }, { kParamFiltS, 0.2f }, { kParamAmpA, 0.001f }, { kParamAmpD, 0.6f }, { kParamAmpS, 0.6f }, { kParamAmpR, 0.2f } };
static constexpr PresetRow kP42[] = { { kParamMode, 4.0f }, { kParamPrismAlgo, 7.0f }, { kParamPrismFB, 0.0f }, { kParamOp1Ratio, 1.0f }, { kParamOp1Level, 1.0f }, { kParamOp1A, 0.001f }, { kParamOp1D, 4.0f }, { kParamOp1S, 0.0f }, { kParamOp1R, 3.0f }, { kParamOp2Ratio, 2.76f }, { kParamOp2Level, 0.5f }, { kParamOp2A, 0.001f }, { kParamOp2D, 3.0f }, { kParamOp2S, 0.0f }, { kParamOp2R, 2.5f }, { kParamOp3Ratio, 5.4f }, { kParamOp3Level, 0.3f }, { kParamOp3A, 0.001f }, { kParamOp3D, 2.0f }, { kParamOp3S, 0.0f }, { kParamOp3R, 1.8f }, { kParamOp4Ratio, 8.93f }, { kParamOp4Level, 0.15f }, { kParamOp4A, 0.001f }, { kParamOp4D, 1.2f }, { kParamOp4S, 0.0f }, { kParamOp4R, 1.2f }, { kParamFilterCutoff, 16000.0f }, { kParamFilterEnvAmt, 0.0f }, { kParamAmpA, 0.001f }, { kParamAmpD, 5.0f }, { kParamAmpS, 0.0f }, { kParamAmpR, 3.5f }, { kParamReverbOn, 1.0f }, { kParamReverbSize, 0.7f }, { kParamReverbDecay, 4.0f }, { kParamReverbMix, 0.3f } };
static constexpr PresetRow kP43[] = { { kParamMasterVol, -2.0f }, { kParamMode, 4.0f }, { kParamPrismAlgo, 0.0f }, { kParamPrismFB, 0.6f }, { kParamOp1Ratio, 1.0f }, { kParamOp1Level, 1.0f }, { kParamOp1A, 0.06f }, { kParamOp1D, 0.3f }, { kParamOp1S, 0.8f }, { kParamOp1R, 0.3f }, { kParamOp2Ratio, 1.0f }, { kParamOp2Level, 0.7f }, { kParamOp2A, 0.1f }, { kParamOp2D, 0.4f }, { kParamOp2S, 0.6f }, { kParamOp2R, 0.3f }, { kParamOp3Ratio, 1.0f }, { kParamOp3Level, 0.5f }, { kParamOp3A, 0.08f }, { kParamOp3D, 0.4f }, { kParamOp3S, 0.5f }, { kParamOp3R, 0.3f }, { kParamOp4Ratio, 1.0f }, { kParamOp4Level, 0.6f }, { kParamOp4A, 0.05f }, { kParamOp4D, 0.3f }, { kParamOp4S, 0.5f }, { kParamOp4R, 0.3f }, { kParamFilterCutoff, 5000.0f }, { kParamFilterRes, 0.1f }, { kParamFilterEnvAmt, 0.4f }, { kParamFiltA, 0.05f }, { kParamFiltD, 0.4f }, { kParamFiltS, 0.5f }, { kParamAmpA, 0.08f }, { kParamAmpD, 0.3f }, { kParamAmpS, 0.75f }, { kParamAmpR, 0.3f } };
static constexpr PresetRow kP44[] = { { kParamMode, 5.0f }, { kParamArpOn, 1.0f }, { kParamOsc1Wave, 0.0f }, { kParamFilterCutoff, 500.0f }, { kParamFilterRes, 0.82f }, { kParamFilterEnvAmt, 0.6f }, { kParamAmpD, 0.3f }, { kParamAmpS, 0.0f }, { kParamAcidAccentAmt, 0.8f }, { kParamAcidSlideTime, 60.0f }, { kParamArpRate, 4.0f }, { kParamArpGate, 0.55f }, { kParamSeqPitch2, 12.0f }, { kParamSeqPitch5, 3.0f }, { kParamSeqPitch7, 12.0f }, { kParamSeqPitch10, 7.0f }, { kParamSeqPitch12, 5.0f }, { kParamSeqPitch14, -5.0f }, { kParamSeqAccent0, 1.0f }, { kParamSeqAccent4, 1.0f }, { kParamSeqAccent8, 1.0f }, { kParamSeqAccent12, 1.0f }, { kParamSeqSlide3, 1.0f }, { kParamSeqSlide7, 1.0f } };
static constexpr PresetRow kP45[] = { { kParamMode, 5.0f }, { kParamArpOn, 1.0f }, { kParamOsc1Wave, 1.0f }, { kParamFilterCutoff, 420.0f }, { kParamFilterRes, 0.3f }, { kParamFilterEnvAmt, 0.5f }, { kParamAmpD, 0.14f }, { kParamAmpS, 0.0f }, { kParamAcidAccentAmt, 0.5f }, { kParamAcidSlideTime, 50.0f }, { kParamArpRate, 4.0f }, { kParamArpGate, 0.45f }, { kParamSeqPitch4, 12.0f }, { kParamSeqPitch6, 7.0f }, { kParamSeqPitch11, 3.0f }, { kParamSeqPitch12, -5.0f }, { kParamSeqAccent0, 1.0f }, { kParamSeqAccent6, 1.0f }, { kParamSeqAccent10, 1.0f } };
static constexpr PresetRow kP46[] = { { kParamMode, 5.0f }, { kParamArpOn, 1.0f }, { kParamOsc1Wave, 0.0f }, { kParamFilterCutoff, 320.0f }, { kParamFilterRes, 0.62f }, { kParamFilterEnvAmt, 0.4f }, { kParamAmpD, 0.45f }, { kParamAmpS, 0.0f }, { kParamAcidAccentAmt, 0.6f }, { kParamAcidSlideTime, 150.0f }, { kParamArpRate, 3.0f }, { kParamArpGate, 0.75f }, { kParamSeqPitch2, -2.0f }, { kParamSeqPitch4, 3.0f }, { kParamSeqPitch6, -5.0f }, { kParamSeqPitch9, 5.0f }, { kParamSeqPitch11, -7.0f }, { kParamSeqPitch13, 2.0f }, { kParamSeqSlide2, 1.0f }, { kParamSeqSlide4, 1.0f }, { kParamSeqSlide6, 1.0f }, { kParamSeqSlide9, 1.0f }, { kParamSeqSlide11, 1.0f }, { kParamSeqSlide13, 1.0f }, { kParamSeqAccent0, 1.0f }, { kParamSeqAccent8, 1.0f } };
static constexpr PresetRow kP47[] = { { kParamMasterVol, -4.0f }, { kParamMode, 5.0f }, { kParamArpOn, 1.0f }, { kParamOsc1Wave, 0.0f }, { kParamFilterCutoff, 600.0f }, { kParamFilterRes, 0.95f }, { kParamFilterEnvAmt, 0.7f }, { kParamAmpD, 0.25f }, { kParamAmpS, 0.0f }, { kParamAcidAccentAmt, 1.0f }, { kParamAcidSlideTime, 55.0f }, { kParamDriveOn, 1.0f }, { kParamDriveAmt, 0.55f }, { kParamDriveType, 0.0f }, { kParamArpRate, 4.0f }, { kParamArpGate, 0.5f }, { kParamSeqPitch3, 12.0f }, { kParamSeqPitch7, 12.0f }, { kParamSeqPitch9, 7.0f }, { kParamSeqPitch11, 10.0f }, { kParamSeqPitch15, -12.0f }, { kParamSeqAccent0, 1.0f }, { kParamSeqAccent2, 1.0f }, { kParamSeqAccent5, 1.0f }, { kParamSeqAccent8, 1.0f }, { kParamSeqAccent11, 1.0f }, { kParamSeqAccent14, 1.0f }, { kParamSeqSlide7, 1.0f }, { kParamSeqSlide11, 1.0f } };
static constexpr PresetRow kP48[] = { { kParamMode, 0.0f }, { kParamOsc1Wave, 0.0f }, { kParamOsc2Wave, 4.0f }, { kParamOsc2Detune, 12.0f }, { kParamOsc2PW, 0.4f }, { kParamSubLevel, 0.35f }, { kParamFilterCutoff, 3000.0f }, { kParamFilterRes, 0.2f }, { kParamFilterEnvAmt, 0.2f }, { kParamAmpA, 1.2f }, { kParamAmpD, 1.0f }, { kParamAmpS, 0.9f }, { kParamAmpR, 3.0f }, { kParamCosmosChorus, 3.0f }, { kParamReverbOn, 1.0f }, { kParamReverbSize, 0.8f }, { kParamReverbDecay, 4.0f }, { kParamReverbMix, 0.3f }, { kParamStereoWidth, 0.9f } };
static constexpr PresetRow kP49[] = { { kParamMasterVol, -3.5f }, { kParamMode, 1.0f }, { kParamOsc2Semi, 0.0f }, { kParamFilterCutoff, 1800.0f }, { kParamFilterRes, 0.35f }, { kParamFilterEnvAmt, 0.6f }, { kParamFiltA, 0.04f }, { kParamFiltD, 0.3f }, { kParamFiltS, 0.4f }, { kParamAmpA, 0.02f }, { kParamAmpD, 0.3f }, { kParamAmpS, 0.8f }, { kParamAmpR, 0.35f }, { kParamPmFenvFilt, 0.35f }, { kParamPmFenvOscA, 0.1f }, { kParamUnisonVoices, 2.0f }, { kParamUnisonDetune, 6.0f }, { kParamStereoWidth, 0.6f } };
static constexpr PresetRow kP50[] = { { kParamMasterVol, -3.0f }, { kParamMode, 2.0f }, { kParamHardSync, 1.0f }, { kParamOsc2Semi, 12.0f }, { kParamFilterCutoff, 4000.0f }, { kParamFilterRes, 0.5f }, { kParamFilterEnvAmt, 0.6f }, { kParamFiltA, 0.01f }, { kParamFiltD, 0.3f }, { kParamFiltS, 0.3f }, { kParamAmpA, 0.005f }, { kParamAmpS, 0.8f }, { kParamAmpR, 0.3f }, { kParamPortaTime, 0.05f }, { kParamDriveOn, 1.0f }, { kParamDriveAmt, 0.4f }, { kParamDelayOn, 1.0f }, { kParamDelaySync, 1.0f }, { kParamDelayDiv, 3.0f }, { kParamDelayMix, 0.25f }, { kParamDelayFB, 0.35f } };
static constexpr PresetRow kP51[] = { { kParamMode, 3.0f }, { kParamOsc3Wave, 3.0f }, { kParamOsc3Level, 0.5f }, { kParamShRate, 6.0f }, { kParamModSrc0, 10.0f }, { kParamModDst0, 5.0f }, { kParamModAmt0, 0.6f }, { kParamModSrc1, 10.0f }, { kParamModDst1, 6.0f }, { kParamModAmt1, 0.3f }, { kParamFilterCutoff, 1500.0f }, { kParamFilterRes, 0.5f }, { kParamFilterEnvAmt, 0.3f }, { kParamAmpA, 0.6f }, { kParamAmpD, 1.0f }, { kParamAmpS, 0.8f }, { kParamAmpR, 3.0f }, { kParamReverbOn, 1.0f }, { kParamReverbSize, 0.6f }, { kParamReverbDecay, 6.0f }, { kParamReverbMix, 0.35f }, { kParamVintage, 0.3f } };
static constexpr PresetRow kP52[] = { { kParamMasterVol, -3.0f }, { kParamMode, 4.0f }, { kParamPrismAlgo, 4.0f }, { kParamPrismFB, 0.0f }, { kParamOp1Ratio, 1.0f }, { kParamOp1Level, 0.9f }, { kParamOp1A, 0.8f }, { kParamOp1D, 2.0f }, { kParamOp1S, 0.7f }, { kParamOp1R, 2.5f }, { kParamOp2Ratio, 2.0f }, { kParamOp2Level, 0.35f }, { kParamOp2A, 1.0f }, { kParamOp2D, 2.0f }, { kParamOp2S, 0.6f }, { kParamOp2R, 2.5f }, { kParamOp3Ratio, 1.0f }, { kParamOp3Level, 0.7f }, { kParamOp3A, 0.8f }, { kParamOp3D, 2.0f }, { kParamOp3S, 0.7f }, { kParamOp3R, 2.5f }, { kParamOp4Ratio, 3.0f }, { kParamOp4Level, 0.25f }, { kParamOp4KeyScale, -0.2f }, { kParamOp4A, 1.0f }, { kParamOp4D, 2.0f }, { kParamOp4S, 0.6f }, { kParamOp4R, 2.5f }, { kParamFilterCutoff, 9000.0f }, { kParamFilterEnvAmt, 0.0f }, { kParamAmpA, 1.0f }, { kParamAmpD, 2.0f }, { kParamAmpS, 0.85f }, { kParamAmpR, 3.5f }, { kParamChorusOn, 1.0f }, { kParamChorusMix, 0.3f }, { kParamReverbOn, 1.0f }, { kParamReverbSize, 0.85f }, { kParamReverbDecay, 6.0f }, { kParamReverbMix, 0.35f }, { kParamStereoWidth, 0.85f } };
static constexpr PresetRow kP53[] = { { kParamMode, 5.0f }, { kParamArpOn, 1.0f }, { kParamOsc1Wave, 0.0f }, { kParamFilterCutoff, 520.0f }, { kParamFilterRes, 0.75f }, { kParamFilterEnvAmt, 0.6f }, { kParamAmpD, 0.3f }, { kParamAmpS, 0.0f }, { kParamAcidAccentAmt, 0.7f }, { kParamAcidSlideTime, 60.0f }, { kParamArpRate, 4.0f }, { kParamArpGate, 0.5f }, { kParamSeqPitch1, 12.0f }, { kParamSeqPitch4, 7.0f }, { kParamSeqPitch6, 3.0f }, { kParamSeqPitch9, 10.0f }, { kParamSeqPitch12, 5.0f }, { kParamSeqPitch14, -5.0f }, { kParamSeqAccent0, 1.0f }, { kParamSeqAccent4, 1.0f }, { kParamSeqAccent8, 1.0f }, { kParamSeqAccent12, 1.0f }, { kParamSeqSlide6, 1.0f }, { kParamSeqSlide14, 1.0f }, { kParamDelayOn, 1.0f }, { kParamDelaySync, 1.0f }, { kParamDelayDiv, 3.0f }, { kParamDelayMix, 0.3f }, { kParamDelayFB, 0.4f }, { kParamDelayPP, 1.0f } };

struct FactoryPreset { const char* name; const PresetRow* rows; int nRows; };
static constexpr FactoryPreset kFactoryPresets[] =
{
    { "Neon Nights", kP00, (int)(sizeof(kP00)/sizeof(PresetRow)) },
    { "Glass Highway", kP01, (int)(sizeof(kP01)/sizeof(PresetRow)) },
    { "Velvet Fog", kP02, (int)(sizeof(kP02)/sizeof(PresetRow)) },
    { "Sunset Strip", kP03, (int)(sizeof(kP03)/sizeof(PresetRow)) },
    { "Crystal Rain", kP04, (int)(sizeof(kP04)/sizeof(PresetRow)) },
    { "Brass Section", kP05, (int)(sizeof(kP05)/sizeof(PresetRow)) },
    { "Wooden Keys", kP06, (int)(sizeof(kP06)/sizeof(PresetRow)) },
    { "Poly Mod Bells", kP07, (int)(sizeof(kP07)/sizeof(PresetRow)) },
    { "Dark Oracle", kP08, (int)(sizeof(kP08)/sizeof(PresetRow)) },
    { "Stab Machine", kP09, (int)(sizeof(kP09)/sizeof(PresetRow)) },
    { "Pulsing Darkness", kP10, (int)(sizeof(kP10)/sizeof(PresetRow)) },
    { "Acid Squelch", kP11, (int)(sizeof(kP11)/sizeof(PresetRow)) },
    { "Screaming Lead", kP12, (int)(sizeof(kP12)/sizeof(PresetRow)) },
    { "Sub Thunder", kP13, (int)(sizeof(kP13)/sizeof(PresetRow)) },
    { "Sync Sweep", kP14, (int)(sizeof(kP14)/sizeof(PresetRow)) },
    { "Upside Down", kP15, (int)(sizeof(kP15)/sizeof(PresetRow)) },
    { "Sci-Fi Computer", kP16, (int)(sizeof(kP16)/sizeof(PresetRow)) },
    { "Horror Drone", kP17, (int)(sizeof(kP17)/sizeof(PresetRow)) },
    { "Voltage Ghost", kP18, (int)(sizeof(kP18)/sizeof(PresetRow)) },
    { "Retro Sequence", kP19, (int)(sizeof(kP19)/sizeof(PresetRow)) },
    { "Midnight Drive", kP20, (int)(sizeof(kP20)/sizeof(PresetRow)) },
    { "Starfield", kP21, (int)(sizeof(kP21)/sizeof(PresetRow)) },
    { "Poly Brass", kP22, (int)(sizeof(kP22)/sizeof(PresetRow)) },
    { "Glass Bells", kP23, (int)(sizeof(kP23)/sizeof(PresetRow)) },
    { "Acid Machine", kP24, (int)(sizeof(kP24)/sizeof(PresetRow)) },
    { "Thunder Sub", kP25, (int)(sizeof(kP25)/sizeof(PresetRow)) },
    { "Voltage Seq", kP26, (int)(sizeof(kP26)/sizeof(PresetRow)) },
    { "Alien Transmission", kP27, (int)(sizeof(kP27)/sizeof(PresetRow)) },
    { "Warm Keys", kP28, (int)(sizeof(kP28)/sizeof(PresetRow)) },
    { "Analog Strings", kP29, (int)(sizeof(kP29)/sizeof(PresetRow)) },
    { "Wobble Bass", kP30, (int)(sizeof(kP30)/sizeof(PresetRow)) },
    { "Tape Lead", kP31, (int)(sizeof(kP31)/sizeof(PresetRow)) },
    { "Drone Machine", kP32, (int)(sizeof(kP32)/sizeof(PresetRow)) },
    { "Arp Factory", kP33, (int)(sizeof(kP33)/sizeof(PresetRow)) },
    { "Fat Fifth", kP34, (int)(sizeof(kP34)/sizeof(PresetRow)) },
    { "Noise Sweep", kP35, (int)(sizeof(kP35)/sizeof(PresetRow)) },
    { "Init Cosmos", kP36, (int)(sizeof(kP36)/sizeof(PresetRow)) },
    { "Init Oracle", kP37, (int)(sizeof(kP37)/sizeof(PresetRow)) },
    { "Init Mono", kP38, (int)(sizeof(kP38)/sizeof(PresetRow)) },
    { "Init Modular", kP39, (int)(sizeof(kP39)/sizeof(PresetRow)) },
    { "Glass Keys", kP40, (int)(sizeof(kP40)/sizeof(PresetRow)) },
    { "Solid Bass", kP41, (int)(sizeof(kP41)/sizeof(PresetRow)) },
    { "Crystal Bells", kP42, (int)(sizeof(kP42)/sizeof(PresetRow)) },
    { "Brass Machine", kP43, (int)(sizeof(kP43)/sizeof(PresetRow)) },
    { "Silver Squelch", kP44, (int)(sizeof(kP44)/sizeof(PresetRow)) },
    { "Rubber Bass", kP45, (int)(sizeof(kP45)/sizeof(PresetRow)) },
    { "Night Crawler", kP46, (int)(sizeof(kP46)/sizeof(PresetRow)) },
    { "Screamer", kP47, (int)(sizeof(kP47)/sizeof(PresetRow)) },
    { "Aurora Drift", kP48, (int)(sizeof(kP48)/sizeof(PresetRow)) },
    { "Regal Brass", kP49, (int)(sizeof(kP49)/sizeof(PresetRow)) },
    { "Siren Lead", kP50, (int)(sizeof(kP50)/sizeof(PresetRow)) },
    { "Nebula Static", kP51, (int)(sizeof(kP51)/sizeof(PresetRow)) },
    { "Glass Cathedral", kP52, (int)(sizeof(kP52)/sizeof(PresetRow)) },
    { "Neon Sequence", kP53, (int)(sizeof(kP53)/sizeof(PresetRow)) },
};
static constexpr int kNumFactoryPresets = (int)(sizeof(kFactoryPresets)/sizeof(kFactoryPresets[0]));
static constexpr int kBaselineRows = (int)(sizeof(kPresetBaseline)/sizeof(PresetRow));
