// Copyright (C) 2026 Dusk Audio — GNU GPL v3.0 or later (see repository LICENSE).
#pragma once
#ifndef DUSKVERB2_VERSION_MAJOR
# define DUSKVERB2_VERSION_MAJOR 0
#endif
#ifndef DUSKVERB2_VERSION_MINOR
# define DUSKVERB2_VERSION_MINOR 1
#endif
#ifndef DUSKVERB2_VERSION_PATCH
# define DUSKVERB2_VERSION_PATCH 0
#endif
#define DUSKVERB2_STRINGIFY_IMPL(x) #x
#define DUSKVERB2_STRINGIFY(x) DUSKVERB2_STRINGIFY_IMPL(x)
#define DUSKVERB2_VERSION_STRING DUSKVERB2_STRINGIFY(DUSKVERB2_VERSION_MAJOR) "." \
                                 DUSKVERB2_STRINGIFY(DUSKVERB2_VERSION_MINOR) "." \
                                 DUSKVERB2_STRINGIFY(DUSKVERB2_VERSION_PATCH)
