#!/usr/bin/env python3
"""Fit the periodic 50/100/200 Hz H2-H7 residual from actual AU renders.

The generated table contains complex residuals expressed as real coefficients
for sine/cosine harmonic bases.  It deliberately reads no 1 kHz or 5 kHz
measurement; those frequencies remain prediction checks.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path


REPO = Path(__file__).resolve().parents[3]
EVIDENCE = REPO / "build-multi-comp-1176/opto-production-harmonics-20260928"
UAD_PATH = EVIDENCE / "lf-expanded-r7-fit-source-uad.json"
MC2_PATH = EVIDENCE / "lf-expanded-r7-fit-source-mc2.json"
OUTPUT = REPO / "plugins/multi-comp/core/MultiCompOptoLfDynamicHarmonics.hpp"
FREQUENCIES = (50, 100, 200)
LEVELS = tuple(range(-40, 1, 4))
GAINS = (0.15, 0.25, 0.35)
PRS = (0.0, 0.35, 0.70, 1.0)
HARMONICS = tuple(range(2, 8))


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def key(row: dict) -> tuple:
    return (row["frequency_hz"], row["input_dbfs"],
            row["peak_reduction_normalised"], row["gain_normalised"],
            row["limit"], row["harmonic"])


def relative_complex(row: dict) -> complex:
    magnitude = 10.0 ** (row["magnitude_dbfs"] / 20.0)
    phase = math.radians(row["relative_phase_degrees"])
    return magnitude * complex(math.cos(phase), math.sin(phase))


def main() -> None:
    uad = {key(row): row for row in json.loads(UAD_PATH.read_text())}
    mc2 = {key(row): row for row in json.loads(MC2_PATH.read_text())}
    values = []
    for limit in (False, True):
        for pr in PRS:
            source_limit = False if pr == 0.0 else limit
            for gain in GAINS:
                for frequency in FREQUENCIES:
                    for level in LEVELS:
                        for harmonic in HARMONICS:
                            row_key = (frequency, level, pr, gain,
                                       source_limit, harmonic)
                            residual = relative_complex(uad[row_key]) \
                                - relative_complex(mc2[row_key])
                            # The render window begins on the input sine's
                            # zero crossing, so a synthesized sin(n theta) has
                            # absolute phase -90 degrees and cos(n theta) has
                            # phase zero. Express those orthogonal axes
                            # relative to the measured MC-2 output H1 phase.
                            fundamental_phase = mc2[row_key][
                                "fundamental_phase_degrees"]
                            sin_phase = math.radians(
                                -90.0 - harmonic * fundamental_phase)
                            cos_phase = math.radians(
                                -harmonic * fundamental_phase)
                            sin_axis = complex(math.cos(sin_phase),
                                               math.sin(sin_phase))
                            cos_axis = complex(math.cos(cos_phase),
                                               math.sin(cos_phase))
                            values.extend(((residual * sin_axis.conjugate()).real,
                                           (residual * cos_axis.conjugate()).real))

    lines = []
    for start in range(0, len(values), 6):
        lines.append("    " + ", ".join(
            f"{value:.10e}f" for value in values[start:start + 6]) + ",")
    header = f'''// Copyright (C) 2026 Dusk Audio, GNU GPL v3.0 or later (see repository LICENSE).
// Generated by tests/fit_opto_lf_dynamic_harmonics.py from actual AU renders.
// Fit frequencies: 50, 100 and 200 Hz only. 1 kHz and 5 kHz are prediction-only.
// UAD map SHA-256: {sha256(UAD_PATH)}
// MC-2 R6 map SHA-256: {sha256(MC2_PATH)}
#pragma once
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>

namespace duskaudio
{{
inline constexpr std::array<float, {len(values)}> kOptoLfDynamicResidualTable{{{{
{chr(10).join(lines)}
}}}};

inline std::array<float, 12> optoLfDynamicResiduals(float inputLevelDb,
                                                    float frequencyHz,
                                                    float peakReduction,
                                                    float gainKnob,
                                                    bool limit) noexcept
{{
    struct Span {{ int lo, hi; float t; }};
    const auto uniformSpan = [](float value, float first, float step, int count) noexcept {{
        const float position = std::clamp((value - first) / step, 0.0f,
                                          static_cast<float>(count - 1));
        const int lo = std::min(static_cast<int>(position), count - 1);
        const int hi = std::min(lo + 1, count - 1);
        return Span{{lo, hi, position - static_cast<float>(lo)}};
    }};
    const auto nonUniformSpan = [](float value, const float* points, int count) noexcept {{
        if (value <= points[0]) return Span{{0, 0, 0.0f}};
        if (value >= points[count - 1]) return Span{{count - 1, count - 1, 0.0f}};
        int hi = 1;
        while (hi < count && value > points[hi]) ++hi;
        const int lo = hi - 1;
        return Span{{lo, hi, (value - points[lo]) / (points[hi] - points[lo])}};
    }};
    constexpr float prPoints[4] = {{0.0f, 0.35f, 0.70f, 1.0f}};
    constexpr float frequencyPoints[3] = {{50.0f, 100.0f, 200.0f}};
    const float pr = std::clamp(peakReduction * 0.01f, 0.0f, 1.0f);
    const float gain = std::clamp(gainKnob * 0.01f, 0.0f, 1.0f);
    const Span ps = nonUniformSpan(pr, prPoints, 4);
    const Span gs = uniformSpan(gain, 0.15f, 0.10f, 3);
    const Span fs = nonUniformSpan(frequencyHz, frequencyPoints, 3);
    const Span ls = uniformSpan(inputLevelDb, -40.0f, 4.0f, 11);
    const int mode = limit ? 1 : 0;
    const auto at = [mode](int pi, int gi, int fi, int li, int coefficient) noexcept {{
        const size_t index = static_cast<size_t>((((((mode * 4 + pi) * 3 + gi)
            * 3 + fi) * 11 + li) * 12 + coefficient));
        return kOptoLfDynamicResidualTable[index];
    }};
    std::array<float, 12> result{{}};
    for (int coefficient = 0; coefficient < 12; ++coefficient)
    {{
        const auto levelMix = [&](int pi, int gi, int fi) noexcept {{
            const float a = at(pi, gi, fi, ls.lo, coefficient);
            return a + (at(pi, gi, fi, ls.hi, coefficient) - a) * ls.t;
        }};
        const auto frequencyMix = [&](int pi, int gi) noexcept {{
            const float a = levelMix(pi, gi, fs.lo);
            return a + (levelMix(pi, gi, fs.hi) - a) * fs.t;
        }};
        const auto gainMix = [&](int pi) noexcept {{
            const float a = frequencyMix(pi, gs.lo);
            return a + (frequencyMix(pi, gs.hi) - a) * gs.t;
        }};
        const float a = gainMix(ps.lo);
        result[static_cast<size_t>(coefficient)] =
            a + (gainMix(ps.hi) - a) * ps.t;
    }}
    return result;
}}
}} // namespace duskaudio
'''
    OUTPUT.write_text(header)
    report = {
        "fit_frequencies_hz": FREQUENCIES,
        "coefficient_count": len(values),
        "minimum_coefficient": min(values), "maximum_coefficient": max(values),
        "uad_sha256": sha256(UAD_PATH), "mc2_sha256": sha256(MC2_PATH),
        "output": str(OUTPUT), "output_sha256": sha256(OUTPUT),
    }
    (EVIDENCE / "lf-dynamic-harmonic-fit.json").write_text(
        json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
