#!/usr/bin/env python3
"""Fit the 1 kHz-only Opto harmonic residual table.

Inputs are actual-AU measurements made by opto_au_harmonic_map.py.  The fit
never reads the 100 Hz or 5 kHz rows: those remain prediction tests.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path


REPO = Path(__file__).resolve().parents[3]
EVIDENCE = REPO / "build-multi-comp-1176/opto-production-harmonics-20260928"
UAD_PATH = EVIDENCE / "harmonics-base-uad.json"
MC2_PATH = EVIDENCE / "harmonics-base-mc2.json"
OUTPUT = REPO / "plugins/multi-comp/core/MultiCompOptoHarmonics.hpp"
LEVELS = tuple(range(-40, 1, 4))
GAINS = (0.15, 0.25, 0.35)
PRS = (0.0, 0.35, 0.70, 1.0)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def key(row: dict) -> tuple:
    return (row["frequency_hz"], row["input_dbfs"],
            row["peak_reduction_normalised"], row["gain_normalised"],
            row["limit"], row["harmonic"])


def relative_complex(row: dict) -> complex:
    magnitude = 10.0 ** (row["magnitude_dbfs"] / 20.0)
    phase = math.radians(row["relative_phase_degrees"])
    return magnitude * complex(math.cos(phase), math.sin(phase))


def residual(reference: dict, baseline: dict) -> tuple[float, bool]:
    """Real residual that makes the final harmonic magnitude equal reference.

    The Chebyshev carrier is in phase (or antiphase for a negative coefficient)
    with Hn relative to H1.  Preserve the baseline's quadrature component and
    solve the remaining real component exactly.  All acceptance-relevant 1 kHz
    rows are feasible; infeasible rows are below the -100 dBFS scoring floor.
    """
    target = abs(relative_complex(reference))
    current = relative_complex(baseline)
    feasible = target >= abs(current.imag)
    wanted_sign = 1.0 if math.cos(math.radians(reference["relative_phase_degrees"])) >= 0.0 else -1.0
    final_real = wanted_sign * math.sqrt(max(target * target - current.imag * current.imag, 0.0))
    return final_real - current.real, feasible


def main() -> None:
    uad_all = json.loads(UAD_PATH.read_text())
    mc2_all = json.loads(MC2_PATH.read_text())
    # This filter is the fit/test firewall.  No non-1-kHz measurement can enter
    # the generated weights or influence model selection.
    uad = {key(row): row for row in uad_all if row["frequency_hz"] == 1000}
    mc2 = {key(row): row for row in mc2_all if row["frequency_hz"] == 1000}
    values = []
    gr_values = []
    infeasible = []
    for limit in (False, True):
        for pr in PRS:
            source_limit = False if pr == 0.0 else limit
            for gain in GAINS:
                for level in LEVELS:
                    base_key = (1000, level, 0.0, gain, False, 2)
                    active_key = (1000, level, pr, gain, source_limit, 2)
                    gr_values.append(max(0.0,
                        mc2[base_key]["fundamental_dbfs"]
                        - mc2[active_key]["fundamental_dbfs"]))
                    for harmonic in range(2, 8):
                        k = (1000, level, pr, gain, source_limit, harmonic)
                        value, feasible = residual(uad[k], mc2[k])
                        values.append(value)
                        if not feasible:
                            infeasible.append({"key": k, "uad_dbfs": uad[k]["magnitude_dbfs"]})

    eligible_infeasible = [row for row in infeasible if row["uad_dbfs"] > -100.0]
    if eligible_infeasible:
        raise RuntimeError(f"real-basis fit cannot reach eligible rows: {eligible_infeasible}")

    lines = []
    for start in range(0, len(values), 6):
        lines.append("    " + ", ".join(f"{value:.10e}f" for value in values[start:start + 6]) + ",")
    gr_lines = []
    for start in range(0, len(gr_values), 11):
        gr_lines.append("    " + ", ".join(f"{value:.9e}f" for value in gr_values[start:start + 11]) + ",")
    header = f'''// Copyright (C) 2026 Dusk Audio, GNU GPL v3.0 or later (see repository LICENSE).
// Generated by tests/fit_opto_harmonics.py from actual AU renders.
// Fit frequency: 1 kHz only. 100 Hz and 5 kHz are prediction-only.
// UAD map SHA-256: {sha256(UAD_PATH)}
// MC-2 base map SHA-256: {sha256(MC2_PATH)}
#pragma once
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>

namespace duskaudio
{{
inline constexpr std::array<float, {len(values)}> kOptoHarmonicResidualTable{{{{
{chr(10).join(lines)}
}}}};
inline constexpr std::array<float, {len(gr_values)}> kOptoHarmonicGrTable{{{{
{chr(10).join(gr_lines)}
}}}};

inline std::array<float, 6> optoHarmonicResiduals(float inputLevelDb,
                                                  float peakReduction,
                                                  float dynamicGrDb,
                                                  float gainKnob,
                                                  bool limit) noexcept
{{
    struct Span {{ int lo, hi; float t; }};
    const auto uniformSpan = [](float value, float first, float step, int count) noexcept {{
        const float position = std::clamp((value - first) / step, 0.0f,
                                          static_cast<float>(count - 1));
        const int lo = std::min(static_cast<int>(position), count - 1);
        const int hi = std::min(lo + 1, count - 1);
        return Span{{lo, hi, position - static_cast<float>(lo)}};
    }};
    const auto nonUniformSpan = [](float value, const float* points, int count) noexcept {{
        if (value <= points[0]) return Span{{0, 0, 0.0f}};
        if (value >= points[count - 1]) return Span{{count - 1, count - 1, 0.0f}};
        int hi = 1;
        while (hi < count && value > points[hi]) ++hi;
        const int lo = hi - 1;
        return Span{{lo, hi, (value - points[lo]) / (points[hi] - points[lo])}};
    }};
    constexpr float prPoints[4] = {{0.0f, 0.35f, 0.70f, 1.0f}};
    const float pr = std::clamp(peakReduction * 0.01f, 0.0f, 1.0f);
    const float gain = std::clamp(gainKnob * 0.01f, 0.0f, 1.0f);
    const Span ps = nonUniformSpan(pr, prPoints, 4);
    const Span gs = uniformSpan(gain, 0.15f, 0.10f, 3);
    // The compression-dependent element is ahead of the cell/Gain path.  P's
    // measured law makes its output harmonic proportional to transmission
    // squared: once in the nonlinear term and once when the result traverses
    // the cell.  Preserve the 1 kHz fit and predict other detector frequencies
    // by only that physical transmission ratio; no 100 Hz/5 kHz target enters.
    const float expectedGrDb = peakReduction <= 15.0f ? 0.0f
        : optoCurveDb(inputLevelDb - optoThresholdDb(peakReduction, limit), limit);
    const float transmissionScale = std::pow(
        10.0f, -(dynamicGrDb - expectedGrDb) * 0.10f);
    const Span ls = uniformSpan(inputLevelDb, -40.0f, 4.0f, 11);
    const float belowScale = inputLevelDb < -40.0f
        ? std::pow(10.0f, (inputLevelDb + 40.0f) * 0.05f) : 1.0f;
    // Do not extrapolate the measured Gain range into the output-ceiling
    // regime. Fade to zero before 0.40; the frozen map remains unaffected.
    const float gainRangeScale = gain < 0.15f ? gain / 0.15f
        : (gain > 0.35f ? std::clamp((0.40f - gain) / 0.05f, 0.0f, 1.0f)
                        : 1.0f);
    const int mode = limit ? 1 : 0;
    const auto at = [mode](int pi, int gi, int li, int h) noexcept {{
        const size_t index = static_cast<size_t>(((((mode * 4 + pi) * 3 + gi)
            * 11 + li) * 6 + h));
        return kOptoHarmonicResidualTable[index];
    }};
    std::array<float, 6> result{{}};
    for (int h = 0; h < 6; ++h)
    {{
        const auto levelMix = [&](int pi, int gi) noexcept {{
            const float a = at(pi, gi, ls.lo, h);
            return a + (at(pi, gi, ls.hi, h) - a) * ls.t;
        }};
        const auto gainMix = [&](int pi) noexcept {{
            const float a = levelMix(pi, gs.lo);
            return a + (levelMix(pi, gs.hi) - a) * gs.t;
        }};
        const float a = gainMix(ps.lo);
        result[static_cast<size_t>(h)] = belowScale * gainRangeScale
            * transmissionScale
            * (a + (gainMix(ps.hi) - a) * ps.t);
    }}
    return result;
}}
}} // namespace duskaudio
'''
    OUTPUT.write_text(header)
    report = {
        "fit_frequency_hz": 1000, "coefficient_count": len(values),
        "gr_coordinate_count": len(gr_values),
        "infeasible_rows": len(infeasible),
        "eligible_infeasible_rows": len(eligible_infeasible),
        "minimum_coefficient": min(values), "maximum_coefficient": max(values),
        "uad_sha256": sha256(UAD_PATH), "mc2_sha256": sha256(MC2_PATH),
        "output": str(OUTPUT), "output_sha256": sha256(OUTPUT),
    }
    (EVIDENCE / "harmonic-fit.json").write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
